# Generated by Django 5.2.6 on 2025-09-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('departure_city', models.CharField(max_length=3)),
                ('arrival_city', models.CharField(max_length=3)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'flight_event',
            },
        ),
    ]
